## Pytorch basics

In [0]:
import torch

In [3]:
x = torch.empty(5, 5)
x

tensor([[0.0000e+00, 0.0000e+00, 6.8664e-44, 7.9874e-44, 6.3058e-44],
        [6.7262e-44, 7.7071e-44, 6.3058e-44, 6.8664e-44, 7.5670e-44],
        [1.1771e-43, 7.0065e-44, 6.8664e-44, 8.1275e-44, 7.2868e-44],
        [7.9874e-44, 8.1275e-44, 7.4269e-44, 7.1466e-44, 6.4460e-44],
        [7.7071e-44, 7.7071e-44, 6.7262e-44, 7.2868e-44, 7.5670e-44]])

In [4]:
torch.rand(2,2)

tensor([[0.0462, 0.0250],
        [0.7451, 0.8604]])

In [11]:
torch.zeros(2,2, dtype=torch.long)

tensor([[0, 0],
        [0, 0]])

In [0]:
??torch.zeros

In [13]:
torch.tensor([[1,2],[4,5]])

tensor([[1, 2],
        [4, 5]])

In [0]:
x = torch.tensor(range(4), dtype = torch.double)

In [22]:
print(x.new_ones(5,3))  # what is the point of this ? 
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([0., 1., 2., 3.], dtype=torch.float64)


In [23]:
torch.randn_like(x)

tensor([-0.6031, -0.6388, -1.2493,  1.4617], dtype=torch.float64)

In [26]:
print(x.shape)  # same 
print(x.size())

torch.Size([4])
torch.Size([4])


In [28]:
x + torch.tensor(range(4), dtype = torch.double)

tensor([0., 2., 4., 6.], dtype=torch.float64)

In [0]:
y = torch.tensor(range(4), dtype = torch.double)

In [30]:
y.add_(x) # y = y + x

tensor([0., 2., 4., 6.], dtype=torch.float64)

In [31]:
y

tensor([0., 2., 4., 6.], dtype=torch.float64)

In [32]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [33]:
x

tensor([[-1.3778, -1.2523,  0.2914,  2.0074],
        [ 0.0446,  0.7125, -0.9100, -1.5203],
        [ 0.7891, -2.1536, -2.2918,  1.0709],
        [ 1.2489, -0.3730,  1.3713,  0.4874]])

In [39]:
x.numpy()

array([[ 0.62224495,  0.7477238 ,  2.2914345 ,  4.007374  ],
       [ 2.044599  ,  2.7124665 ,  1.0900159 ,  0.47973967],
       [ 2.789056  , -0.15356159, -0.29184008,  3.0709243 ],
       [ 3.2488632 ,  1.6269643 ,  3.3712604 ,  2.4874258 ]],
      dtype=float32)

In [40]:
y = x.numpy()
print(y)

[[ 0.62224495  0.7477238   2.2914345   4.007374  ]
 [ 2.044599    2.7124665   1.0900159   0.47973967]
 [ 2.789056   -0.15356159 -0.29184008  3.0709243 ]
 [ 3.2488632   1.6269643   3.3712604   2.4874258 ]]


In [41]:
x.add_(1)  # x and y both change values
x, y

(tensor([[1.6222, 1.7477, 3.2914, 5.0074],
         [3.0446, 3.7125, 2.0900, 1.4797],
         [3.7891, 0.8464, 0.7082, 4.0709],
         [4.2489, 2.6270, 4.3713, 3.4874]]),
 array([[1.622245 , 1.7477238, 3.2914345, 5.007374 ],
        [3.044599 , 3.7124665, 2.090016 , 1.4797397],
        [3.789056 , 0.8464384, 0.7081599, 4.0709243],
        [4.248863 , 2.6269643, 4.3712606, 3.4874258]], dtype=float32))

In [42]:
x = x + 1 # only change x
x, y

(tensor([[2.6222, 2.7477, 4.2914, 6.0074],
         [4.0446, 4.7125, 3.0900, 2.4797],
         [4.7891, 1.8464, 1.7082, 5.0709],
         [5.2489, 3.6270, 5.3713, 4.4874]]),
 array([[1.622245 , 1.7477238, 3.2914345, 5.007374 ],
        [3.044599 , 3.7124665, 2.090016 , 1.4797397],
        [3.789056 , 0.8464384, 0.7081599, 4.0709243],
        [4.248863 , 2.6269643, 4.3712606, 3.4874258]], dtype=float32))

In [47]:
import numpy as np
a = np.random.randn(5)
a

array([ 1.27008064,  0.38176109, -1.86975933,  0.49286453,  0.08534811])

In [48]:
b = torch.from_numpy(a)
np.add(a, 1, out = a)
print(a)
print(b)

[ 2.27008064  1.38176109 -0.86975933  1.49286453  1.08534811]
tensor([ 2.2701,  1.3818, -0.8698,  1.4929,  1.0853], dtype=torch.float64)


In [49]:
a = a + 1
print(a)
print(b)

[3.27008064 2.38176109 0.13024067 2.49286453 2.08534811]
tensor([ 2.2701,  1.3818, -0.8698,  1.4929,  1.0853], dtype=torch.float64)


In [50]:
torch.cuda.is_available()

True

In [52]:
device = torch.device("cuda")
device

device(type='cuda')

In [0]:
y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
x = x.to(device)                       # or just use strings ``.to("cuda")``
z = x + y

In [54]:
z

tensor([[3.6222, 3.7477, 5.2914, 7.0074],
        [5.0446, 5.7125, 4.0900, 3.4797],
        [5.7891, 2.8464, 2.7082, 6.0709],
        [6.2489, 4.6270, 6.3713, 5.4874]], device='cuda:0')

In [55]:
x

tensor([[2.6222, 2.7477, 4.2914, 6.0074],
        [4.0446, 4.7125, 3.0900, 2.4797],
        [4.7891, 1.8464, 1.7082, 5.0709],
        [5.2489, 3.6270, 5.3713, 4.4874]], device='cuda:0')

## Autograd

In [85]:
x = torch.ones(2,2, requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [86]:
y = x + 2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [66]:
p = x * 2
p

tensor([[2., 2.],
        [2., 2.]], grad_fn=<MulBackward0>)

In [61]:
print(y.grad_fn)

In [62]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [87]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [88]:
z = y * y * 3
out = z.mean()
z, out

(tensor([[27., 27.],
         [27., 27.]], grad_fn=<MulBackward0>),
 tensor(27., grad_fn=<MeanBackward0>))

In [89]:
x.grad == None

True

In [90]:
out.backward()
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

In [0]:
x = torch.ones(2, 1, requires_grad=True)

In [0]:
y = x + 2
z = y * y * 3

In [102]:
out = z.mean()
out.backward()
x.grad

tensor([[9.],
        [9.]])

## y = g(x) R^n -> R^m vector valued 
## z = f(y)  R^m -> R^1 scalar valued
## dz/dy = (dy/dx).t() @ dz/dy

### dy/dx m * n
### dz/dy m * 1

In [104]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([-444.7076,   27.8274, 1279.7865], grad_fn=<MulBackward0>)


In [0]:
## Dont run 
y.backward()
## RuntimeError: grad can be implicitly created only for scalar outputs

## Pytorch NN

In [0]:
import torch
import torch.nn as nn
import torch.nn.functional as F


class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        # 1 input image channel, 6 output channels, 3x3 square convolution
        # kernel
        self.conv1 = nn.Conv2d(1, 6, 3)
        self.conv2 = nn.Conv2d(6, 16, 3)
        # an affine operation: y = Wx + b
        self.fc1 = nn.Linear(16 * 6 * 6, 120)  # 6*6 from image dimension
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        # Max pooling over a (2, 2) window
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        # If the size is a square you can only specify a single number
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

    def num_flat_features(self, x):
        size = x.size()[1:]  # all dimensions except the batch dimension
        num_features = 1
        for s in size:
            num_features *= s
        return num_features


net = Net()
print(net)